# Generated by Django 2.2.13 on 2020-07-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CousreModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cnnum', models.IntegerField(unique=True)),
                ('marks', models.FloatField()),
                ('subject', models.ManyToManyField(to='app7.CousreModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacuiltyModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cnnum', models.IntegerField(unique=True)),
                ('salary', models.FloatField()),
                ('subject', models.ManyToManyField(to='app7.CousreModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
